### ISSUE TITLE
black / white icon depending on status bar color

### ISSUE THREAD

**Issue by sataset** [actuallymentor/battery#9] opened 2022-09-28 16:04 UTC
Icon is adapted for light status bar only.

![image](https://user-images.githubusercontent.com/28687456/192829207-a93e7778-5d69-4853-ab92-f1eebb04f342.png)

These threads might be helpful:
- [link 1](https://stackoverflow.com/questions/62685948/macos-big-sur-detect-dark-menu-bar-system-tray%29)
- [link 2](https://developer.apple.com/forums/thread/662322)

**Comment by actuallymentor** [comment] 2022-10-13 16:48
Ah weird, it should work:

<img width="69" alt="image" src="https://user-images.githubusercontent.com/9071382/195656803-5d975a1f-8fa6-4642-bc82-69b1d1b3a3d1.png">

What version number does `battery` show?

**Comment by sataset** [comment] 2022-10-13 16:56
Installed the latest 1.0.3 from brew and experienced the same effect.

I think the icon becomes normal during the charge or wallpaper change, but clicking "Disable 80% battery limit" reproduces the issue.

Currently this happens for me on both light and dark macOS themes with Catalina dynamic wallpaper during the night time.

**Comment by waterlou** [comment] 2022-10-15 14:39
same here, 1.0.3, installed from homebrew.

**Comment by actuallymentor** [comment] 2022-12-17 13:23
Note to self: might look at at some point. No high prio. If anyone figures out the source of this I'd welcome a PR.

**Comment by actuallymentor** [comment] 2023-02-05 14:49
Closing as I can't reproduce.

**Closed by actuallymentor** 2023-02-05 14:49 UTC
Labels: bug, help wanted (PR welcome), wontfix
