### ISSUE TITLE
Surfing Mode: Maintain a charge RANGE instead of value

### ISSUE THREAD

**Issue by dempstert** [actuallymentor/battery#174] opened 2023-09-04 02:18 UTC
Instead of maintaining a fixed charge level, eg 80%, can we have the feature to maintain a charge level between a lower and upper threshold?

Maintaing a fixed percentage means a lot of switching between charging / discharging mode.

I assume it's better for battery health in the long term to run between (e.g.) 50% and 90% smoothly, than to sit at 80% and constantly modulate.

**Comment by pfitoussi** [comment] 2023-09-05 10:21
It seems that you can apply this feature with :
```
battery charge 90
battery discharge 50
```

**Comment by my4ng** [comment] 2023-09-06 09:42
> battery charge 90
battery discharge 50

these are only one-off commands, cf. `battery maintain`.

**Comment by dempstert** [comment] 2023-09-07 00:05
@my4ng Does `battery maintain` allow settings for upper & lower windows ?

**Comment by my4ng** [comment] 2023-09-07 13:30
@dempstert I do not believe so. I haven't read through the source code, so I can only suspect that it is a binary operation (i.e. `< threshold`) rather than a ranged one. On the other hand, Al Dente does support the so-called "sailing mode", which means this is not a hardware limitation either.

**Comment by earthsound** [comment] 2023-10-24 00:55
Dupe of #150

**Comment by actuallymentor** [comment] 2024-01-17 12:22
Closing as duplicate of #222, let's continue the convo there

**Closed by actuallymentor** 2024-01-17 12:22 UTC
