### ISSUE TITLE
battery maintain support charging range

### ISSUE THREAD

**Issue by kaixinzheng** [actuallymentor/battery#185] opened 2023-09-26 02:19 UTC
Wonderful app 👏

Sometimes my laptop unplugged and plugged frequently,  if it unplugged and use 2% battery it would be 78%, and then charging to 80%, again and again, charging too frequently.

so if we add a range settings in battery maintain, like 'battery maintain 75 90', 
it will start charging only below or equal 75%,
and discharging at 90%. 

haha thank you～

**Comment by actuallymentor** [comment] 2024-01-17 12:16
Duplicate of #222

**Closed by actuallymentor** 2024-01-17 12:16 UTC
