### ISSUE TITLE
Can we have an option to turn on/off low-power mode

### ISSUE THREAD

**Issue by victorwon** [actuallymentor/battery#152] opened 2023-06-29 14:38 UTC
**Is your feature request related to a problem? Please describe.**
It'd be of great  convenience to have a menu option to turn on/off low-power mode, it's especially useful for m2 chips and the system settings are buried too deep to use. 

It'd be even better to have a keyboard short-cut associated with it, and corresponding badge on the menubar icon to indicate whether the low-power mode is enabled.

**Describe the solution you'd like**
mac commands:
- to get status: `pmset -g|grep "lowpowermode"|tail -c 2`
- to set low-power mode: `sudo pmset -a lowpowermode 1`
- to unset:  `sudo pmset -a lowpowermode 0`

**Comment by actuallymentor** [comment] 2023-07-20 11:42
What is the advantage of doing this? I'm not familiar with this setting.

**Comment by actuallymentor** [comment] 2023-07-20 12:01
Duplicate of #110, please continue discussion there

**Closed by actuallymentor** 2023-07-20 12:01 UTC
Labels: ⏱️ waiting
