### ISSUE TITLE
menu icon needs a negative glyph

### ISSUE THREAD

**Issue by winstonford** [actuallymentor/battery#77] opened 2023-02-15 19:59 UTC
The [sweet] menu bar icon shows black when others show white.  I believe what is needed is a single glyph mask, a negative, so that a white or black background will show thru glyph depending on dark or light mode in macOS.

<img width="332" alt="Screenshot 2023-02-15 at 2 55 28 PM" src="https://user-images.githubusercontent.com/4634622/219138703-7b08b89c-f80c-4c17-b6b6-a4edb0374f5d.png">

**Comment by winstonford** [comment] 2023-02-15 20:26
Updated to 0.8, and issue persists. 

<img width="307" alt="image" src="https://user-images.githubusercontent.com/4634622/219146019-e441f9cc-6c83-4170-bdf2-2f8b298940b6.png">

<img width="231" alt="image" src="https://user-images.githubusercontent.com/4634622/219146127-ee9cafd7-b9f8-4577-81a9-deb9e9316034.png">

**Comment by earthsound** [comment] 2023-02-15 23:08
duplicate of #56 and/or #57?

**Comment by actuallymentor** [comment] 2023-03-06 16:40
Should be fixed in latest release [v1.1.1](https://github.com/actuallymentor/battery/releases/tag/v1.1.1)

**Closed by actuallymentor** 2023-03-06 16:40 UTC
