### ISSUE TITLE
Menu bar icon suddenly white

### ISSUE THREAD

**Issue by kristiankruse** [actuallymentor/battery#56] opened 2023-02-09 05:06 UTC
After installing 1.0.6 and also upgraded to 1.0.7 the menu bar icon is now white—whereas it used to be black to match the rest of the icons.

**Comment by schabrolles** [comment] 2023-02-11 12:47
I had the opposite behaviour ... install 1.0.7, try icon is black while it should be white

**Comment by actuallymentor** [comment] 2023-02-11 21:27
Hmm it should keep to your light/dark system setting. Screenshot?

**Comment by schabrolles** [comment] 2023-02-12 10:22
Here it is ... I'm using macOS Ventura .... this mean that light mode does not mean dark tray icon ... It depends of your wallpaper background. I'm with "auto" light/dark mode in macOS. My background is more dark than light. So even during the day (light mode) tray icon must be white.

Here is a screenshot during the day, light them in macOS, all the tray icons are white except "battery.app"
<img width="529" alt="Screenshot 2023-02-12 at 11 13 54" src="https://user-images.githubusercontent.com/19491077/218305431-574e18a4-4d6e-4cc0-ad4c-39b3a87d36fb.png">

**Comment by abstractrealism** [comment] 2023-02-13 14:32
I'm experiencing the same on Monterrey. Not sure if it's because of background color or what, but all icons besides battery are white during the day. Has been the case since I installed it a while ago, not a new issue. I thought it was intentional haha

**Comment by kristiankruse** [comment] 2023-02-14 04:20
<img width="443" alt="screenshot 2023-02-13 at 20 20 37" src="https://user-images.githubusercontent.com/564745/218638506-e4db4506-02e1-4d82-9a0f-3030693ac64a.png">

**Comment by Neifab** [comment] 2023-02-15 13:02
MacOS Ventura 13.2.1, version 1.0.8

<img width="169" alt="Capture d’écran 2023-02-15 à 13 51 52" src="https://user-images.githubusercontent.com/76597174/219034443-7cc94baf-e002-4187-871d-396a3908f298.png">

**Comment by nomadplanet** [comment] 2023-02-27 08:34
The menu bar does not necessarily update to a white theme when switching to dark mode or a black theme when switching off the dark mode.  It's all about the wallpaper colour behind it. For instance, my menu bar icons are always white whether I'm in dark or light mode. 

The problem is that battery follows entirely the dark/light mode to decide which icon variant to apply.

**Comment by Neifab** [comment] 2023-02-27 11:40
> 

Yes, should be easy to fix

**Comment by earthsound** [comment] 2023-03-01 22:13
@actuallymentor this article describes how to set up [macOS monochrome template images](https://bjango.com/articles/designingmenubarextras/#colour-and-template-images) to resolve this.

**Comment by actuallymentor** [comment] 2023-03-06 16:40
Should be fixed in latest release [v1.1.1](https://github.com/actuallymentor/battery/releases/tag/v1.1.1)

**Closed by actuallymentor** 2023-03-06 16:40 UTC
Labels: ⏱️ waiting

**Comment by nomadplanet** [comment] 2023-03-06 18:17
Indeed, it is 👍 
Thanks
