### ISSUE TITLE
Battery charged to 100% despite limit

### ISSUE THREAD

**Issue by rexovas** [actuallymentor/battery#135] opened 2023-04-29 22:17 UTC
Nifty tool - First came across Al Dente which seemed WAY too bloated + no way I was gonna stare at that pasta icon all day.  

As title suggests

Installed the battery cli yesterday - computer has not been rebooted, though it was with the lid closed and unplugged overnight.  Today I plugged in the computer to charge when the battery was around 49%.  I left home expecting to come back and find it charged to 80%, however it was charged to 100%.  See the below screenshot.

<img width="617" alt="Screenshot 2023-04-29 at 6 13 56 PM" src="https://user-images.githubusercontent.com/33384036/235326332-8ecf678a-23c5-4f86-b617-35824125ece1.png">

I've since run `battery maintain stop` and `battery maintain 80` and I can see now that it reports smc charging as disabled... but hoping this won't be a frequent issue.

<img width="894" alt="Screenshot 2023-04-29 at 6 19 27 PM" src="https://user-images.githubusercontent.com/33384036/235326392-ddaa01f4-1cf9-48ba-8c6e-cb9375952421.png">

One thing to note - I did not disable Apple's built in optimize battery charging until after the first time I ran battery maintain 80, so I'm wondering if that had something to do with it.

**Comment by rexovas** [comment] 2023-04-30 20:21
Tried again last night - plugged it in right before heading to sleep.  This morning it was charged only to 85% and reported `smc charging disabled`, but still above 80%.  Not quite sure why that is.

<img width="561" alt="Screenshot 2023-04-30 at 4 19 56 PM" src="https://user-images.githubusercontent.com/33384036/235374526-40e85e09-5f2a-41a6-82b2-b493412e6b94.png">

**Comment by charlie0129** [comment] 2023-05-10 16:24
This is cause by sleeping, see #123 . I did some analysis in that issue. Probably you can check that issue out.

**Comment by rexovas** [comment] 2023-05-10 18:17
Thanks for the reply, though if sleep is causing the issue, why does the computer not charge to 100% despite being plugged in/lid closed overnight? 

Since that first time it charged to 100%, I haven’t had it do that again, but it has charged ~1-5% above the limit I’ve set.

**Comment by charlie0129** [comment] 2023-05-11 01:23
Charging a couple of percent more seems normal to me if you rebooted your computer or did some other things that caused the script to stop. Looking at the logs should make it easier to debug.

**Comment by rexovas** [comment] 2023-05-11 03:23
Where are the logs located for the cli version

**Comment by charlie0129** [comment] 2023-05-11 06:36
> Where are the logs located for the cli version?

You can run `battery logs` to see it.

**Comment by actuallymentor** [comment] 2023-07-20 11:44
Closing as duplicate of #123

**Closed by actuallymentor** 2023-07-20 11:44 UTC
