### ISSUE TITLE
magsafe led

### ISSUE THREAD

**Issue by p205s** [actuallymentor/battery#161] opened 2023-07-30 18:47 UTC
Thank you, great app. Add MagSafe LED orange -- battery charging, green -- battery charged.

**Comment by whiterock** [comment] 2023-08-03 10:05
https://github.com/actuallymentor/battery/issues/71

…

**Comment by actuallymentor** [comment] 2023-08-20 12:04
Dupe of #71, no issue template. Closing.

**Closed by actuallymentor** 2023-08-20 12:04 UTC
